package com.mbg.demo.model;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table b_collect_data_log
 *
 * @mbg.generated do_not_delete_during_merge Tue Nov 06 11:40:18 CST 2018
 */
public class DataLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.id
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   龙湖公司业务单元 MA 为总部 C1 为房产 C2 为商圈 C3 为冠寓 C4 为物业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.bu
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String bu;

    /**
     * Database Column Remarks:
     *   用户手机号 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.mobile
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   用户手机号所在城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.mobile_city
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String mobileCity;

    /**
     * Database Column Remarks:
     *   用户手机号所在省份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.mobile_province
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String mobileProvince;

    /**
     * Database Column Remarks:
     *   用户在我数据库中的uid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.uid
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String uid;

    /**
     * Database Column Remarks:
     *   用户在系统中的登录名,目前使用mobile
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.user_name
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   用户追踪id用来做非登录状态用户标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.trance_id
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String tranceId;

    /**
     * Database Column Remarks:
     *   用户浏览器上一页
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.refer
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String refer;

    /**
     * Database Column Remarks:
     *   用户系统说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.user_agent
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String userAgent;

    /**
     * Database Column Remarks:
     *   浏览器名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.browser_name
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String browserName;

    /**
     * Database Column Remarks:
     *   浏览器版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.browser_version
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String browserVersion;

    /**
     * Database Column Remarks:
     *   操作系统名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.os_name
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String osName;

    /**
     * Database Column Remarks:
     *   操作系统版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.os_version
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String osVersion;

    /**
     * Database Column Remarks:
     *   用户应用/活动名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.app
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String app;

    /**
     * Database Column Remarks:
     *   用户应用/活动版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.app_version
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String appVersion;

    /**
     * Database Column Remarks:
     *   用户设备,pc,h5,pad,app
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.device
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String device;

    /**
     * Database Column Remarks:
     *   用户请求ip
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.ip
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String ip;

    /**
     * Database Column Remarks:
     *   用户请求ip城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.ip_city
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String ipCity;

    /**
     * Database Column Remarks:
     *   用户请求ip省份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.ip_province
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String ipProvince;

    /**
     * Database Column Remarks:
     *   用户当前页url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.current_url
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String currentUrl;

    /**
     * Database Column Remarks:
     *   页面title
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.title
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String title;

    /**
     * Database Column Remarks:
     *   页面域名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.domain
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String domain;

    /**
     * Database Column Remarks:
     *   访问时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.visit_time
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private LocalDateTime visitTime;

    /**
     * Database Column Remarks:
     *   用户页面渠道标识 可以是button-name 可以是页面入口标识 也可以是预先设定好的渠道标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.publish_channel
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String publishChannel;

    /**
     * Database Column Remarks:
     *   用户操作标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.event
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String event;

    /**
     * Database Column Remarks:
     *   用户操作结果 可以是数字的0成功,1失败 可以是接口返回的数据,最好json串
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.result
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String result;

    /**
     * Database Column Remarks:
     *   数据创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.create_time
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   数据创建来源 龙民节,即可以用longmin_ma 6.18 可以用longfor_618
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.source
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String source;

    /**
     * Database Column Remarks:
     *   用户操作时候,选定的我方系统中标识的用户所在区域
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.area_id
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String areaId;

    /**
     * Database Column Remarks:
     *   系统埋点入口 C1 : 底部bar”买好房" C2 : 分会场入口、抢、底部bar“逛天街”C3 : 分会场入口、抢、底部bar“租冠寓”C4 : 分会场入口、抢、底部bar“玩千丁”
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_collect_data_log.entry
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private String entry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_collect_data_log
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.id
     *
     * @return the value of b_collect_data_log.id
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.id
     *
     * @param id the value for b_collect_data_log.id
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.bu
     *
     * @return the value of b_collect_data_log.bu
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getBu() {
        return bu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.bu
     *
     * @param bu the value for b_collect_data_log.bu
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setBu(String bu) {
        this.bu = bu == null ? null : bu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.mobile
     *
     * @return the value of b_collect_data_log.mobile
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.mobile
     *
     * @param mobile the value for b_collect_data_log.mobile
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.mobile_city
     *
     * @return the value of b_collect_data_log.mobile_city
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getMobileCity() {
        return mobileCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.mobile_city
     *
     * @param mobileCity the value for b_collect_data_log.mobile_city
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setMobileCity(String mobileCity) {
        this.mobileCity = mobileCity == null ? null : mobileCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.mobile_province
     *
     * @return the value of b_collect_data_log.mobile_province
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getMobileProvince() {
        return mobileProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.mobile_province
     *
     * @param mobileProvince the value for b_collect_data_log.mobile_province
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setMobileProvince(String mobileProvince) {
        this.mobileProvince = mobileProvince == null ? null : mobileProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.uid
     *
     * @return the value of b_collect_data_log.uid
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.uid
     *
     * @param uid the value for b_collect_data_log.uid
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.user_name
     *
     * @return the value of b_collect_data_log.user_name
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.user_name
     *
     * @param userName the value for b_collect_data_log.user_name
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.trance_id
     *
     * @return the value of b_collect_data_log.trance_id
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getTranceId() {
        return tranceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.trance_id
     *
     * @param tranceId the value for b_collect_data_log.trance_id
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setTranceId(String tranceId) {
        this.tranceId = tranceId == null ? null : tranceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.refer
     *
     * @return the value of b_collect_data_log.refer
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getRefer() {
        return refer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.refer
     *
     * @param refer the value for b_collect_data_log.refer
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setRefer(String refer) {
        this.refer = refer == null ? null : refer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.user_agent
     *
     * @return the value of b_collect_data_log.user_agent
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.user_agent
     *
     * @param userAgent the value for b_collect_data_log.user_agent
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.browser_name
     *
     * @return the value of b_collect_data_log.browser_name
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getBrowserName() {
        return browserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.browser_name
     *
     * @param browserName the value for b_collect_data_log.browser_name
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setBrowserName(String browserName) {
        this.browserName = browserName == null ? null : browserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.browser_version
     *
     * @return the value of b_collect_data_log.browser_version
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getBrowserVersion() {
        return browserVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.browser_version
     *
     * @param browserVersion the value for b_collect_data_log.browser_version
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setBrowserVersion(String browserVersion) {
        this.browserVersion = browserVersion == null ? null : browserVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.os_name
     *
     * @return the value of b_collect_data_log.os_name
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getOsName() {
        return osName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.os_name
     *
     * @param osName the value for b_collect_data_log.os_name
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setOsName(String osName) {
        this.osName = osName == null ? null : osName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.os_version
     *
     * @return the value of b_collect_data_log.os_version
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.os_version
     *
     * @param osVersion the value for b_collect_data_log.os_version
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion == null ? null : osVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.app
     *
     * @return the value of b_collect_data_log.app
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.app
     *
     * @param app the value for b_collect_data_log.app
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setApp(String app) {
        this.app = app == null ? null : app.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.app_version
     *
     * @return the value of b_collect_data_log.app_version
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.app_version
     *
     * @param appVersion the value for b_collect_data_log.app_version
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.device
     *
     * @return the value of b_collect_data_log.device
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.device
     *
     * @param device the value for b_collect_data_log.device
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.ip
     *
     * @return the value of b_collect_data_log.ip
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.ip
     *
     * @param ip the value for b_collect_data_log.ip
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.ip_city
     *
     * @return the value of b_collect_data_log.ip_city
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getIpCity() {
        return ipCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.ip_city
     *
     * @param ipCity the value for b_collect_data_log.ip_city
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setIpCity(String ipCity) {
        this.ipCity = ipCity == null ? null : ipCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.ip_province
     *
     * @return the value of b_collect_data_log.ip_province
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getIpProvince() {
        return ipProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.ip_province
     *
     * @param ipProvince the value for b_collect_data_log.ip_province
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setIpProvince(String ipProvince) {
        this.ipProvince = ipProvince == null ? null : ipProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.current_url
     *
     * @return the value of b_collect_data_log.current_url
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getCurrentUrl() {
        return currentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.current_url
     *
     * @param currentUrl the value for b_collect_data_log.current_url
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setCurrentUrl(String currentUrl) {
        this.currentUrl = currentUrl == null ? null : currentUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.title
     *
     * @return the value of b_collect_data_log.title
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.title
     *
     * @param title the value for b_collect_data_log.title
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.domain
     *
     * @return the value of b_collect_data_log.domain
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.domain
     *
     * @param domain the value for b_collect_data_log.domain
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.visit_time
     *
     * @return the value of b_collect_data_log.visit_time
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public LocalDateTime getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.visit_time
     *
     * @param visitTime the value for b_collect_data_log.visit_time
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setVisitTime(LocalDateTime visitTime) {
        this.visitTime = visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.publish_channel
     *
     * @return the value of b_collect_data_log.publish_channel
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getPublishChannel() {
        return publishChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.publish_channel
     *
     * @param publishChannel the value for b_collect_data_log.publish_channel
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setPublishChannel(String publishChannel) {
        this.publishChannel = publishChannel == null ? null : publishChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.event
     *
     * @return the value of b_collect_data_log.event
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.event
     *
     * @param event the value for b_collect_data_log.event
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.result
     *
     * @return the value of b_collect_data_log.result
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.result
     *
     * @param result the value for b_collect_data_log.result
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.create_time
     *
     * @return the value of b_collect_data_log.create_time
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.create_time
     *
     * @param createTime the value for b_collect_data_log.create_time
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.source
     *
     * @return the value of b_collect_data_log.source
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.source
     *
     * @param source the value for b_collect_data_log.source
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.area_id
     *
     * @return the value of b_collect_data_log.area_id
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.area_id
     *
     * @param areaId the value for b_collect_data_log.area_id
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_collect_data_log.entry
     *
     * @return the value of b_collect_data_log.entry
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public String getEntry() {
        return entry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_collect_data_log.entry
     *
     * @param entry the value for b_collect_data_log.entry
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void setEntry(String entry) {
        this.entry = entry == null ? null : entry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collect_data_log
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bu=").append(bu);
        sb.append(", mobile=").append(mobile);
        sb.append(", mobileCity=").append(mobileCity);
        sb.append(", mobileProvince=").append(mobileProvince);
        sb.append(", uid=").append(uid);
        sb.append(", userName=").append(userName);
        sb.append(", tranceId=").append(tranceId);
        sb.append(", refer=").append(refer);
        sb.append(", userAgent=").append(userAgent);
        sb.append(", browserName=").append(browserName);
        sb.append(", browserVersion=").append(browserVersion);
        sb.append(", osName=").append(osName);
        sb.append(", osVersion=").append(osVersion);
        sb.append(", app=").append(app);
        sb.append(", appVersion=").append(appVersion);
        sb.append(", device=").append(device);
        sb.append(", ip=").append(ip);
        sb.append(", ipCity=").append(ipCity);
        sb.append(", ipProvince=").append(ipProvince);
        sb.append(", currentUrl=").append(currentUrl);
        sb.append(", title=").append(title);
        sb.append(", domain=").append(domain);
        sb.append(", visitTime=").append(visitTime);
        sb.append(", publishChannel=").append(publishChannel);
        sb.append(", event=").append(event);
        sb.append(", result=").append(result);
        sb.append(", createTime=").append(createTime);
        sb.append(", source=").append(source);
        sb.append(", areaId=").append(areaId);
        sb.append(", entry=").append(entry);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}