package com.mbg.demo.model;

import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import com.mbg.demo.model.DataLogExample.Criteria;
import java.io.Serializable;
import java.sql.Types;
import java.time.LocalDateTime;
import java.util.List;

@SuppressWarnings("unused")
public class DataLogExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collect_data_log
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public DataLogExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collect_data_log
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collect_data_log
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_collect_data_log
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_collect_data_log
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBuIsNull() {
            addCriterion("bu is null");
            return (Criteria) this;
        }

        public Criteria andBuIsNotNull() {
            addCriterion("bu is not null");
            return (Criteria) this;
        }

        public Criteria andBuEqualTo(String value) {
            addCriterion("bu =", value, "bu");
            return (Criteria) this;
        }

        public Criteria andBuNotEqualTo(String value) {
            addCriterion("bu <>", value, "bu");
            return (Criteria) this;
        }

        public Criteria andBuGreaterThan(String value) {
            addCriterion("bu >", value, "bu");
            return (Criteria) this;
        }

        public Criteria andBuGreaterThanOrEqualTo(String value) {
            addCriterion("bu >=", value, "bu");
            return (Criteria) this;
        }

        public Criteria andBuLessThan(String value) {
            addCriterion("bu <", value, "bu");
            return (Criteria) this;
        }

        public Criteria andBuLessThanOrEqualTo(String value) {
            addCriterion("bu <=", value, "bu");
            return (Criteria) this;
        }

        public Criteria andBuLike(String value) {
            addCriterion("bu like", value, "bu");
            return (Criteria) this;
        }

        public Criteria andBuNotLike(String value) {
            addCriterion("bu not like", value, "bu");
            return (Criteria) this;
        }

        public Criteria andBuIn(List<String> values) {
            addCriterion("bu in", values, "bu");
            return (Criteria) this;
        }

        public Criteria andBuNotIn(List<String> values) {
            addCriterion("bu not in", values, "bu");
            return (Criteria) this;
        }

        public Criteria andBuBetween(String value1, String value2) {
            addCriterion("bu between", value1, value2, "bu");
            return (Criteria) this;
        }

        public Criteria andBuNotBetween(String value1, String value2) {
            addCriterion("bu not between", value1, value2, "bu");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileCityIsNull() {
            addCriterion("mobile_city is null");
            return (Criteria) this;
        }

        public Criteria andMobileCityIsNotNull() {
            addCriterion("mobile_city is not null");
            return (Criteria) this;
        }

        public Criteria andMobileCityEqualTo(String value) {
            addCriterion("mobile_city =", value, "mobileCity");
            return (Criteria) this;
        }

        public Criteria andMobileCityNotEqualTo(String value) {
            addCriterion("mobile_city <>", value, "mobileCity");
            return (Criteria) this;
        }

        public Criteria andMobileCityGreaterThan(String value) {
            addCriterion("mobile_city >", value, "mobileCity");
            return (Criteria) this;
        }

        public Criteria andMobileCityGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_city >=", value, "mobileCity");
            return (Criteria) this;
        }

        public Criteria andMobileCityLessThan(String value) {
            addCriterion("mobile_city <", value, "mobileCity");
            return (Criteria) this;
        }

        public Criteria andMobileCityLessThanOrEqualTo(String value) {
            addCriterion("mobile_city <=", value, "mobileCity");
            return (Criteria) this;
        }

        public Criteria andMobileCityLike(String value) {
            addCriterion("mobile_city like", value, "mobileCity");
            return (Criteria) this;
        }

        public Criteria andMobileCityNotLike(String value) {
            addCriterion("mobile_city not like", value, "mobileCity");
            return (Criteria) this;
        }

        public Criteria andMobileCityIn(List<String> values) {
            addCriterion("mobile_city in", values, "mobileCity");
            return (Criteria) this;
        }

        public Criteria andMobileCityNotIn(List<String> values) {
            addCriterion("mobile_city not in", values, "mobileCity");
            return (Criteria) this;
        }

        public Criteria andMobileCityBetween(String value1, String value2) {
            addCriterion("mobile_city between", value1, value2, "mobileCity");
            return (Criteria) this;
        }

        public Criteria andMobileCityNotBetween(String value1, String value2) {
            addCriterion("mobile_city not between", value1, value2, "mobileCity");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceIsNull() {
            addCriterion("mobile_province is null");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceIsNotNull() {
            addCriterion("mobile_province is not null");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceEqualTo(String value) {
            addCriterion("mobile_province =", value, "mobileProvince");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceNotEqualTo(String value) {
            addCriterion("mobile_province <>", value, "mobileProvince");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceGreaterThan(String value) {
            addCriterion("mobile_province >", value, "mobileProvince");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_province >=", value, "mobileProvince");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceLessThan(String value) {
            addCriterion("mobile_province <", value, "mobileProvince");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceLessThanOrEqualTo(String value) {
            addCriterion("mobile_province <=", value, "mobileProvince");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceLike(String value) {
            addCriterion("mobile_province like", value, "mobileProvince");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceNotLike(String value) {
            addCriterion("mobile_province not like", value, "mobileProvince");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceIn(List<String> values) {
            addCriterion("mobile_province in", values, "mobileProvince");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceNotIn(List<String> values) {
            addCriterion("mobile_province not in", values, "mobileProvince");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceBetween(String value1, String value2) {
            addCriterion("mobile_province between", value1, value2, "mobileProvince");
            return (Criteria) this;
        }

        public Criteria andMobileProvinceNotBetween(String value1, String value2) {
            addCriterion("mobile_province not between", value1, value2, "mobileProvince");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andTranceIdIsNull() {
            addCriterion("trance_id is null");
            return (Criteria) this;
        }

        public Criteria andTranceIdIsNotNull() {
            addCriterion("trance_id is not null");
            return (Criteria) this;
        }

        public Criteria andTranceIdEqualTo(String value) {
            addCriterion("trance_id =", value, "tranceId");
            return (Criteria) this;
        }

        public Criteria andTranceIdNotEqualTo(String value) {
            addCriterion("trance_id <>", value, "tranceId");
            return (Criteria) this;
        }

        public Criteria andTranceIdGreaterThan(String value) {
            addCriterion("trance_id >", value, "tranceId");
            return (Criteria) this;
        }

        public Criteria andTranceIdGreaterThanOrEqualTo(String value) {
            addCriterion("trance_id >=", value, "tranceId");
            return (Criteria) this;
        }

        public Criteria andTranceIdLessThan(String value) {
            addCriterion("trance_id <", value, "tranceId");
            return (Criteria) this;
        }

        public Criteria andTranceIdLessThanOrEqualTo(String value) {
            addCriterion("trance_id <=", value, "tranceId");
            return (Criteria) this;
        }

        public Criteria andTranceIdLike(String value) {
            addCriterion("trance_id like", value, "tranceId");
            return (Criteria) this;
        }

        public Criteria andTranceIdNotLike(String value) {
            addCriterion("trance_id not like", value, "tranceId");
            return (Criteria) this;
        }

        public Criteria andTranceIdIn(List<String> values) {
            addCriterion("trance_id in", values, "tranceId");
            return (Criteria) this;
        }

        public Criteria andTranceIdNotIn(List<String> values) {
            addCriterion("trance_id not in", values, "tranceId");
            return (Criteria) this;
        }

        public Criteria andTranceIdBetween(String value1, String value2) {
            addCriterion("trance_id between", value1, value2, "tranceId");
            return (Criteria) this;
        }

        public Criteria andTranceIdNotBetween(String value1, String value2) {
            addCriterion("trance_id not between", value1, value2, "tranceId");
            return (Criteria) this;
        }

        public Criteria andReferIsNull() {
            addCriterion("refer is null");
            return (Criteria) this;
        }

        public Criteria andReferIsNotNull() {
            addCriterion("refer is not null");
            return (Criteria) this;
        }

        public Criteria andReferEqualTo(String value) {
            addCriterion("refer =", value, "refer");
            return (Criteria) this;
        }

        public Criteria andReferNotEqualTo(String value) {
            addCriterion("refer <>", value, "refer");
            return (Criteria) this;
        }

        public Criteria andReferGreaterThan(String value) {
            addCriterion("refer >", value, "refer");
            return (Criteria) this;
        }

        public Criteria andReferGreaterThanOrEqualTo(String value) {
            addCriterion("refer >=", value, "refer");
            return (Criteria) this;
        }

        public Criteria andReferLessThan(String value) {
            addCriterion("refer <", value, "refer");
            return (Criteria) this;
        }

        public Criteria andReferLessThanOrEqualTo(String value) {
            addCriterion("refer <=", value, "refer");
            return (Criteria) this;
        }

        public Criteria andReferLike(String value) {
            addCriterion("refer like", value, "refer");
            return (Criteria) this;
        }

        public Criteria andReferNotLike(String value) {
            addCriterion("refer not like", value, "refer");
            return (Criteria) this;
        }

        public Criteria andReferIn(List<String> values) {
            addCriterion("refer in", values, "refer");
            return (Criteria) this;
        }

        public Criteria andReferNotIn(List<String> values) {
            addCriterion("refer not in", values, "refer");
            return (Criteria) this;
        }

        public Criteria andReferBetween(String value1, String value2) {
            addCriterion("refer between", value1, value2, "refer");
            return (Criteria) this;
        }

        public Criteria andReferNotBetween(String value1, String value2) {
            addCriterion("refer not between", value1, value2, "refer");
            return (Criteria) this;
        }

        public Criteria andUserAgentIsNull() {
            addCriterion("user_agent is null");
            return (Criteria) this;
        }

        public Criteria andUserAgentIsNotNull() {
            addCriterion("user_agent is not null");
            return (Criteria) this;
        }

        public Criteria andUserAgentEqualTo(String value) {
            addCriterion("user_agent =", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentNotEqualTo(String value) {
            addCriterion("user_agent <>", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentGreaterThan(String value) {
            addCriterion("user_agent >", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentGreaterThanOrEqualTo(String value) {
            addCriterion("user_agent >=", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentLessThan(String value) {
            addCriterion("user_agent <", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentLessThanOrEqualTo(String value) {
            addCriterion("user_agent <=", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentLike(String value) {
            addCriterion("user_agent like", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentNotLike(String value) {
            addCriterion("user_agent not like", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentIn(List<String> values) {
            addCriterion("user_agent in", values, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentNotIn(List<String> values) {
            addCriterion("user_agent not in", values, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentBetween(String value1, String value2) {
            addCriterion("user_agent between", value1, value2, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentNotBetween(String value1, String value2) {
            addCriterion("user_agent not between", value1, value2, "userAgent");
            return (Criteria) this;
        }

        public Criteria andBrowserNameIsNull() {
            addCriterion("browser_name is null");
            return (Criteria) this;
        }

        public Criteria andBrowserNameIsNotNull() {
            addCriterion("browser_name is not null");
            return (Criteria) this;
        }

        public Criteria andBrowserNameEqualTo(String value) {
            addCriterion("browser_name =", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameNotEqualTo(String value) {
            addCriterion("browser_name <>", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameGreaterThan(String value) {
            addCriterion("browser_name >", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameGreaterThanOrEqualTo(String value) {
            addCriterion("browser_name >=", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameLessThan(String value) {
            addCriterion("browser_name <", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameLessThanOrEqualTo(String value) {
            addCriterion("browser_name <=", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameLike(String value) {
            addCriterion("browser_name like", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameNotLike(String value) {
            addCriterion("browser_name not like", value, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameIn(List<String> values) {
            addCriterion("browser_name in", values, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameNotIn(List<String> values) {
            addCriterion("browser_name not in", values, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameBetween(String value1, String value2) {
            addCriterion("browser_name between", value1, value2, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserNameNotBetween(String value1, String value2) {
            addCriterion("browser_name not between", value1, value2, "browserName");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionIsNull() {
            addCriterion("browser_version is null");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionIsNotNull() {
            addCriterion("browser_version is not null");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionEqualTo(String value) {
            addCriterion("browser_version =", value, "browserVersion");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionNotEqualTo(String value) {
            addCriterion("browser_version <>", value, "browserVersion");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionGreaterThan(String value) {
            addCriterion("browser_version >", value, "browserVersion");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionGreaterThanOrEqualTo(String value) {
            addCriterion("browser_version >=", value, "browserVersion");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionLessThan(String value) {
            addCriterion("browser_version <", value, "browserVersion");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionLessThanOrEqualTo(String value) {
            addCriterion("browser_version <=", value, "browserVersion");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionLike(String value) {
            addCriterion("browser_version like", value, "browserVersion");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionNotLike(String value) {
            addCriterion("browser_version not like", value, "browserVersion");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionIn(List<String> values) {
            addCriterion("browser_version in", values, "browserVersion");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionNotIn(List<String> values) {
            addCriterion("browser_version not in", values, "browserVersion");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionBetween(String value1, String value2) {
            addCriterion("browser_version between", value1, value2, "browserVersion");
            return (Criteria) this;
        }

        public Criteria andBrowserVersionNotBetween(String value1, String value2) {
            addCriterion("browser_version not between", value1, value2, "browserVersion");
            return (Criteria) this;
        }

        public Criteria andOsNameIsNull() {
            addCriterion("os_name is null");
            return (Criteria) this;
        }

        public Criteria andOsNameIsNotNull() {
            addCriterion("os_name is not null");
            return (Criteria) this;
        }

        public Criteria andOsNameEqualTo(String value) {
            addCriterion("os_name =", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameNotEqualTo(String value) {
            addCriterion("os_name <>", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameGreaterThan(String value) {
            addCriterion("os_name >", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameGreaterThanOrEqualTo(String value) {
            addCriterion("os_name >=", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameLessThan(String value) {
            addCriterion("os_name <", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameLessThanOrEqualTo(String value) {
            addCriterion("os_name <=", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameLike(String value) {
            addCriterion("os_name like", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameNotLike(String value) {
            addCriterion("os_name not like", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameIn(List<String> values) {
            addCriterion("os_name in", values, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameNotIn(List<String> values) {
            addCriterion("os_name not in", values, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameBetween(String value1, String value2) {
            addCriterion("os_name between", value1, value2, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameNotBetween(String value1, String value2) {
            addCriterion("os_name not between", value1, value2, "osName");
            return (Criteria) this;
        }

        public Criteria andOsVersionIsNull() {
            addCriterion("os_version is null");
            return (Criteria) this;
        }

        public Criteria andOsVersionIsNotNull() {
            addCriterion("os_version is not null");
            return (Criteria) this;
        }

        public Criteria andOsVersionEqualTo(String value) {
            addCriterion("os_version =", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotEqualTo(String value) {
            addCriterion("os_version <>", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionGreaterThan(String value) {
            addCriterion("os_version >", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionGreaterThanOrEqualTo(String value) {
            addCriterion("os_version >=", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLessThan(String value) {
            addCriterion("os_version <", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLessThanOrEqualTo(String value) {
            addCriterion("os_version <=", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLike(String value) {
            addCriterion("os_version like", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotLike(String value) {
            addCriterion("os_version not like", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionIn(List<String> values) {
            addCriterion("os_version in", values, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotIn(List<String> values) {
            addCriterion("os_version not in", values, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionBetween(String value1, String value2) {
            addCriterion("os_version between", value1, value2, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotBetween(String value1, String value2) {
            addCriterion("os_version not between", value1, value2, "osVersion");
            return (Criteria) this;
        }

        public Criteria andAppIsNull() {
            addCriterion("app is null");
            return (Criteria) this;
        }

        public Criteria andAppIsNotNull() {
            addCriterion("app is not null");
            return (Criteria) this;
        }

        public Criteria andAppEqualTo(String value) {
            addCriterion("app =", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppNotEqualTo(String value) {
            addCriterion("app <>", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppGreaterThan(String value) {
            addCriterion("app >", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppGreaterThanOrEqualTo(String value) {
            addCriterion("app >=", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppLessThan(String value) {
            addCriterion("app <", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppLessThanOrEqualTo(String value) {
            addCriterion("app <=", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppLike(String value) {
            addCriterion("app like", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppNotLike(String value) {
            addCriterion("app not like", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppIn(List<String> values) {
            addCriterion("app in", values, "app");
            return (Criteria) this;
        }

        public Criteria andAppNotIn(List<String> values) {
            addCriterion("app not in", values, "app");
            return (Criteria) this;
        }

        public Criteria andAppBetween(String value1, String value2) {
            addCriterion("app between", value1, value2, "app");
            return (Criteria) this;
        }

        public Criteria andAppNotBetween(String value1, String value2) {
            addCriterion("app not between", value1, value2, "app");
            return (Criteria) this;
        }

        public Criteria andAppVersionIsNull() {
            addCriterion("app_version is null");
            return (Criteria) this;
        }

        public Criteria andAppVersionIsNotNull() {
            addCriterion("app_version is not null");
            return (Criteria) this;
        }

        public Criteria andAppVersionEqualTo(String value) {
            addCriterion("app_version =", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotEqualTo(String value) {
            addCriterion("app_version <>", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionGreaterThan(String value) {
            addCriterion("app_version >", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionGreaterThanOrEqualTo(String value) {
            addCriterion("app_version >=", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLessThan(String value) {
            addCriterion("app_version <", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLessThanOrEqualTo(String value) {
            addCriterion("app_version <=", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLike(String value) {
            addCriterion("app_version like", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotLike(String value) {
            addCriterion("app_version not like", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionIn(List<String> values) {
            addCriterion("app_version in", values, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotIn(List<String> values) {
            addCriterion("app_version not in", values, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionBetween(String value1, String value2) {
            addCriterion("app_version between", value1, value2, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotBetween(String value1, String value2) {
            addCriterion("app_version not between", value1, value2, "appVersion");
            return (Criteria) this;
        }

        public Criteria andDeviceIsNull() {
            addCriterion("device is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIsNotNull() {
            addCriterion("device is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceEqualTo(String value) {
            addCriterion("device =", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceNotEqualTo(String value) {
            addCriterion("device <>", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceGreaterThan(String value) {
            addCriterion("device >", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceGreaterThanOrEqualTo(String value) {
            addCriterion("device >=", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceLessThan(String value) {
            addCriterion("device <", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceLessThanOrEqualTo(String value) {
            addCriterion("device <=", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceLike(String value) {
            addCriterion("device like", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceNotLike(String value) {
            addCriterion("device not like", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceIn(List<String> values) {
            addCriterion("device in", values, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceNotIn(List<String> values) {
            addCriterion("device not in", values, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceBetween(String value1, String value2) {
            addCriterion("device between", value1, value2, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceNotBetween(String value1, String value2) {
            addCriterion("device not between", value1, value2, "device");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpCityIsNull() {
            addCriterion("ip_city is null");
            return (Criteria) this;
        }

        public Criteria andIpCityIsNotNull() {
            addCriterion("ip_city is not null");
            return (Criteria) this;
        }

        public Criteria andIpCityEqualTo(String value) {
            addCriterion("ip_city =", value, "ipCity");
            return (Criteria) this;
        }

        public Criteria andIpCityNotEqualTo(String value) {
            addCriterion("ip_city <>", value, "ipCity");
            return (Criteria) this;
        }

        public Criteria andIpCityGreaterThan(String value) {
            addCriterion("ip_city >", value, "ipCity");
            return (Criteria) this;
        }

        public Criteria andIpCityGreaterThanOrEqualTo(String value) {
            addCriterion("ip_city >=", value, "ipCity");
            return (Criteria) this;
        }

        public Criteria andIpCityLessThan(String value) {
            addCriterion("ip_city <", value, "ipCity");
            return (Criteria) this;
        }

        public Criteria andIpCityLessThanOrEqualTo(String value) {
            addCriterion("ip_city <=", value, "ipCity");
            return (Criteria) this;
        }

        public Criteria andIpCityLike(String value) {
            addCriterion("ip_city like", value, "ipCity");
            return (Criteria) this;
        }

        public Criteria andIpCityNotLike(String value) {
            addCriterion("ip_city not like", value, "ipCity");
            return (Criteria) this;
        }

        public Criteria andIpCityIn(List<String> values) {
            addCriterion("ip_city in", values, "ipCity");
            return (Criteria) this;
        }

        public Criteria andIpCityNotIn(List<String> values) {
            addCriterion("ip_city not in", values, "ipCity");
            return (Criteria) this;
        }

        public Criteria andIpCityBetween(String value1, String value2) {
            addCriterion("ip_city between", value1, value2, "ipCity");
            return (Criteria) this;
        }

        public Criteria andIpCityNotBetween(String value1, String value2) {
            addCriterion("ip_city not between", value1, value2, "ipCity");
            return (Criteria) this;
        }

        public Criteria andIpProvinceIsNull() {
            addCriterion("ip_province is null");
            return (Criteria) this;
        }

        public Criteria andIpProvinceIsNotNull() {
            addCriterion("ip_province is not null");
            return (Criteria) this;
        }

        public Criteria andIpProvinceEqualTo(String value) {
            addCriterion("ip_province =", value, "ipProvince");
            return (Criteria) this;
        }

        public Criteria andIpProvinceNotEqualTo(String value) {
            addCriterion("ip_province <>", value, "ipProvince");
            return (Criteria) this;
        }

        public Criteria andIpProvinceGreaterThan(String value) {
            addCriterion("ip_province >", value, "ipProvince");
            return (Criteria) this;
        }

        public Criteria andIpProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("ip_province >=", value, "ipProvince");
            return (Criteria) this;
        }

        public Criteria andIpProvinceLessThan(String value) {
            addCriterion("ip_province <", value, "ipProvince");
            return (Criteria) this;
        }

        public Criteria andIpProvinceLessThanOrEqualTo(String value) {
            addCriterion("ip_province <=", value, "ipProvince");
            return (Criteria) this;
        }

        public Criteria andIpProvinceLike(String value) {
            addCriterion("ip_province like", value, "ipProvince");
            return (Criteria) this;
        }

        public Criteria andIpProvinceNotLike(String value) {
            addCriterion("ip_province not like", value, "ipProvince");
            return (Criteria) this;
        }

        public Criteria andIpProvinceIn(List<String> values) {
            addCriterion("ip_province in", values, "ipProvince");
            return (Criteria) this;
        }

        public Criteria andIpProvinceNotIn(List<String> values) {
            addCriterion("ip_province not in", values, "ipProvince");
            return (Criteria) this;
        }

        public Criteria andIpProvinceBetween(String value1, String value2) {
            addCriterion("ip_province between", value1, value2, "ipProvince");
            return (Criteria) this;
        }

        public Criteria andIpProvinceNotBetween(String value1, String value2) {
            addCriterion("ip_province not between", value1, value2, "ipProvince");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlIsNull() {
            addCriterion("current_url is null");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlIsNotNull() {
            addCriterion("current_url is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlEqualTo(String value) {
            addCriterion("current_url =", value, "currentUrl");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlNotEqualTo(String value) {
            addCriterion("current_url <>", value, "currentUrl");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlGreaterThan(String value) {
            addCriterion("current_url >", value, "currentUrl");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlGreaterThanOrEqualTo(String value) {
            addCriterion("current_url >=", value, "currentUrl");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlLessThan(String value) {
            addCriterion("current_url <", value, "currentUrl");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlLessThanOrEqualTo(String value) {
            addCriterion("current_url <=", value, "currentUrl");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlLike(String value) {
            addCriterion("current_url like", value, "currentUrl");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlNotLike(String value) {
            addCriterion("current_url not like", value, "currentUrl");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlIn(List<String> values) {
            addCriterion("current_url in", values, "currentUrl");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlNotIn(List<String> values) {
            addCriterion("current_url not in", values, "currentUrl");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlBetween(String value1, String value2) {
            addCriterion("current_url between", value1, value2, "currentUrl");
            return (Criteria) this;
        }

        public Criteria andCurrentUrlNotBetween(String value1, String value2) {
            addCriterion("current_url not between", value1, value2, "currentUrl");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andDomainIsNull() {
            addCriterion("domain is null");
            return (Criteria) this;
        }

        public Criteria andDomainIsNotNull() {
            addCriterion("domain is not null");
            return (Criteria) this;
        }

        public Criteria andDomainEqualTo(String value) {
            addCriterion("domain =", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotEqualTo(String value) {
            addCriterion("domain <>", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThan(String value) {
            addCriterion("domain >", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThanOrEqualTo(String value) {
            addCriterion("domain >=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThan(String value) {
            addCriterion("domain <", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThanOrEqualTo(String value) {
            addCriterion("domain <=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLike(String value) {
            addCriterion("domain like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotLike(String value) {
            addCriterion("domain not like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainIn(List<String> values) {
            addCriterion("domain in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotIn(List<String> values) {
            addCriterion("domain not in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainBetween(String value1, String value2) {
            addCriterion("domain between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotBetween(String value1, String value2) {
            addCriterion("domain not between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andVisitTimeIsNull() {
            addCriterion("visit_time is null");
            return (Criteria) this;
        }

        public Criteria andVisitTimeIsNotNull() {
            addCriterion("visit_time is not null");
            return (Criteria) this;
        }

        public Criteria andVisitTimeEqualTo(LocalDateTime value) {
            addCriterion("visit_time =", value, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeNotEqualTo(LocalDateTime value) {
            addCriterion("visit_time <>", value, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeGreaterThan(LocalDateTime value) {
            addCriterion("visit_time >", value, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("visit_time >=", value, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeLessThan(LocalDateTime value) {
            addCriterion("visit_time <", value, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("visit_time <=", value, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeIn(List<LocalDateTime> values) {
            addCriterion("visit_time in", values, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeNotIn(List<LocalDateTime> values) {
            addCriterion("visit_time not in", values, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("visit_time between", value1, value2, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("visit_time not between", value1, value2, "visitTime");
            return (Criteria) this;
        }

        public Criteria andPublishChannelIsNull() {
            addCriterion("publish_channel is null");
            return (Criteria) this;
        }

        public Criteria andPublishChannelIsNotNull() {
            addCriterion("publish_channel is not null");
            return (Criteria) this;
        }

        public Criteria andPublishChannelEqualTo(String value) {
            addCriterion("publish_channel =", value, "publishChannel");
            return (Criteria) this;
        }

        public Criteria andPublishChannelNotEqualTo(String value) {
            addCriterion("publish_channel <>", value, "publishChannel");
            return (Criteria) this;
        }

        public Criteria andPublishChannelGreaterThan(String value) {
            addCriterion("publish_channel >", value, "publishChannel");
            return (Criteria) this;
        }

        public Criteria andPublishChannelGreaterThanOrEqualTo(String value) {
            addCriterion("publish_channel >=", value, "publishChannel");
            return (Criteria) this;
        }

        public Criteria andPublishChannelLessThan(String value) {
            addCriterion("publish_channel <", value, "publishChannel");
            return (Criteria) this;
        }

        public Criteria andPublishChannelLessThanOrEqualTo(String value) {
            addCriterion("publish_channel <=", value, "publishChannel");
            return (Criteria) this;
        }

        public Criteria andPublishChannelLike(String value) {
            addCriterion("publish_channel like", value, "publishChannel");
            return (Criteria) this;
        }

        public Criteria andPublishChannelNotLike(String value) {
            addCriterion("publish_channel not like", value, "publishChannel");
            return (Criteria) this;
        }

        public Criteria andPublishChannelIn(List<String> values) {
            addCriterion("publish_channel in", values, "publishChannel");
            return (Criteria) this;
        }

        public Criteria andPublishChannelNotIn(List<String> values) {
            addCriterion("publish_channel not in", values, "publishChannel");
            return (Criteria) this;
        }

        public Criteria andPublishChannelBetween(String value1, String value2) {
            addCriterion("publish_channel between", value1, value2, "publishChannel");
            return (Criteria) this;
        }

        public Criteria andPublishChannelNotBetween(String value1, String value2) {
            addCriterion("publish_channel not between", value1, value2, "publishChannel");
            return (Criteria) this;
        }

        public Criteria andEventIsNull() {
            addCriterion("event is null");
            return (Criteria) this;
        }

        public Criteria andEventIsNotNull() {
            addCriterion("event is not null");
            return (Criteria) this;
        }

        public Criteria andEventEqualTo(String value) {
            addCriterion("event =", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventNotEqualTo(String value) {
            addCriterion("event <>", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventGreaterThan(String value) {
            addCriterion("event >", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventGreaterThanOrEqualTo(String value) {
            addCriterion("event >=", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventLessThan(String value) {
            addCriterion("event <", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventLessThanOrEqualTo(String value) {
            addCriterion("event <=", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventLike(String value) {
            addCriterion("event like", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventNotLike(String value) {
            addCriterion("event not like", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventIn(List<String> values) {
            addCriterion("event in", values, "event");
            return (Criteria) this;
        }

        public Criteria andEventNotIn(List<String> values) {
            addCriterion("event not in", values, "event");
            return (Criteria) this;
        }

        public Criteria andEventBetween(String value1, String value2) {
            addCriterion("event between", value1, value2, "event");
            return (Criteria) this;
        }

        public Criteria andEventNotBetween(String value1, String value2) {
            addCriterion("event not between", value1, value2, "event");
            return (Criteria) this;
        }

        public Criteria andResultIsNull() {
            addCriterion("result is null");
            return (Criteria) this;
        }

        public Criteria andResultIsNotNull() {
            addCriterion("result is not null");
            return (Criteria) this;
        }

        public Criteria andResultEqualTo(String value) {
            addCriterion("result =", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotEqualTo(String value) {
            addCriterion("result <>", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThan(String value) {
            addCriterion("result >", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThanOrEqualTo(String value) {
            addCriterion("result >=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThan(String value) {
            addCriterion("result <", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThanOrEqualTo(String value) {
            addCriterion("result <=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLike(String value) {
            addCriterion("result like", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotLike(String value) {
            addCriterion("result not like", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultIn(List<String> values) {
            addCriterion("result in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotIn(List<String> values) {
            addCriterion("result not in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultBetween(String value1, String value2) {
            addCriterion("result between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotBetween(String value1, String value2) {
            addCriterion("result not between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("area_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("area_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(String value) {
            addCriterion("area_id =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(String value) {
            addCriterion("area_id <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(String value) {
            addCriterion("area_id >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(String value) {
            addCriterion("area_id >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(String value) {
            addCriterion("area_id <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(String value) {
            addCriterion("area_id <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLike(String value) {
            addCriterion("area_id like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotLike(String value) {
            addCriterion("area_id not like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<String> values) {
            addCriterion("area_id in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<String> values) {
            addCriterion("area_id not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(String value1, String value2) {
            addCriterion("area_id between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(String value1, String value2) {
            addCriterion("area_id not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andEntryIsNull() {
            addCriterion("entry is null");
            return (Criteria) this;
        }

        public Criteria andEntryIsNotNull() {
            addCriterion("entry is not null");
            return (Criteria) this;
        }

        public Criteria andEntryEqualTo(String value) {
            addCriterion("entry =", value, "entry");
            return (Criteria) this;
        }

        public Criteria andEntryNotEqualTo(String value) {
            addCriterion("entry <>", value, "entry");
            return (Criteria) this;
        }

        public Criteria andEntryGreaterThan(String value) {
            addCriterion("entry >", value, "entry");
            return (Criteria) this;
        }

        public Criteria andEntryGreaterThanOrEqualTo(String value) {
            addCriterion("entry >=", value, "entry");
            return (Criteria) this;
        }

        public Criteria andEntryLessThan(String value) {
            addCriterion("entry <", value, "entry");
            return (Criteria) this;
        }

        public Criteria andEntryLessThanOrEqualTo(String value) {
            addCriterion("entry <=", value, "entry");
            return (Criteria) this;
        }

        public Criteria andEntryLike(String value) {
            addCriterion("entry like", value, "entry");
            return (Criteria) this;
        }

        public Criteria andEntryNotLike(String value) {
            addCriterion("entry not like", value, "entry");
            return (Criteria) this;
        }

        public Criteria andEntryIn(List<String> values) {
            addCriterion("entry in", values, "entry");
            return (Criteria) this;
        }

        public Criteria andEntryNotIn(List<String> values) {
            addCriterion("entry not in", values, "entry");
            return (Criteria) this;
        }

        public Criteria andEntryBetween(String value1, String value2) {
            addCriterion("entry between", value1, value2, "entry");
            return (Criteria) this;
        }

        public Criteria andEntryNotBetween(String value1, String value2) {
            addCriterion("entry not between", value1, value2, "entry");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_collect_data_log
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 06 11:40:18 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table b_collect_data_log
     *
     * @mbg.generated Tue Nov 06 11:40:18 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]
		//--------------------------------------------------					
														ID(1, Types.BIGINT, false, "id"),
		/** 龙湖公司业务单元 MA 为总部 C1 为房产 C2 为商圈 C3 为冠寓 C4 为物业 */
														BU(2, Types.VARCHAR, false, "bu"),
		/** 用户手机号  */								MOBILE(2, Types.VARCHAR, false, "mobile"),
		/** 用户手机号所在城市 */						MOBILE_CITY(2, Types.VARCHAR, false, "mobile_city"),
		/** 用户手机号所在省份 */						MOBILE_PROVINCE(2, Types.VARCHAR, false, "mobile_province"),
		/** 用户在我数据库中的uid */					UID(2, Types.VARCHAR, false, "uid"),
		/** 用户在系统中的登录名,目前使用mobile */		USER_NAME(2, Types.VARCHAR, false, "user_name"),
		/** 用户追踪id用来做非登录状态用户标识 */		TRANCE_ID(2, Types.VARCHAR, false, "trance_id"),
		/** 用户浏览器上一页 */							REFER(2, Types.VARCHAR, false, "refer"),
		/** 用户系统说明 */								USER_AGENT(2, Types.VARCHAR, false, "user_agent"),
		/** 浏览器名称 */								BROWSER_NAME(2, Types.VARCHAR, false, "browser_name"),
		/** 浏览器版本号 */								BROWSER_VERSION(2, Types.VARCHAR, false, "browser_version"),
		/** 操作系统名称 */								OS_NAME(2, Types.VARCHAR, false, "os_name"),
		/** 操作系统版本号 */							OS_VERSION(2, Types.VARCHAR, false, "os_version"),
		/** 用户应用/活动名称 */						APP(2, Types.VARCHAR, false, "app"),
		/** 用户应用/活动版本 */						APP_VERSION(2, Types.VARCHAR, false, "app_version"),
		/** 用户设备,pc,h5,pad,app */					DEVICE(2, Types.VARCHAR, false, "device"),
		/** 用户请求ip */								IP(2, Types.VARCHAR, false, "ip"),
		/** 用户请求ip城市 */							IP_CITY(2, Types.VARCHAR, false, "ip_city"),
		/** 用户请求ip省份 */							IP_PROVINCE(2, Types.VARCHAR, false, "ip_province"),
		/** 用户当前页url */							CURRENT_URL(2, Types.VARCHAR, false, "current_url"),
		/** 页面title */								TITLE(2, Types.VARCHAR, false, "title"),
		/** 页面域名 */									DOMAIN(2, Types.VARCHAR, false, "domain"),
		/** 访问时间 */									VISIT_TIME(2, Types.TIMESTAMP, false, "visit_time"),
		/** 用户页面渠道标识 可以是button-name 可以是页面入口标识 也可以是预先设定好的渠道标识 */
														PUBLISH_CHANNEL(2, Types.VARCHAR, false, "publish_channel"),
		/** 用户操作标识 */								EVENT(2, Types.VARCHAR, false, "event"),
		/** 用户操作结果 可以是数字的0成功,1失败 可以是接口返回的数据,最好json串 */
														RESULT(2, Types.VARCHAR, false, "result"),
		/** 数据创建时间 */								CREATE_TIME(2, Types.TIMESTAMP, false, "create_time"),
		/** 数据创建来源 龙民节,即可以用longmin_ma 6.18 可以用longfor_618 */
														SOURCE(2, Types.VARCHAR, false, "source"),
		/** 用户操作时候,选定的我方系统中标识的用户所在区域 */
														AREA_ID(2, Types.VARCHAR, false, "area_id"),
		/** 系统埋点入口 C1 : 底部bar”买好房" C2 : 分会场入口、抢、底部bar“逛天街”C3 : 分会场入口、抢、底部bar“租冠寓”C4 : 分会场入口、抢、底部bar“玩千丁” */
														ENTRY(2, Types.VARCHAR, false, "entry");

        private final CItem CITEM_OBJECT;

        C(int type, int jdbcType, boolean delimited, String columnName) {
            CITEM_OBJECT = new CItem(type, jdbcType, delimited, columnName, null , "`", "`");
        }

        public int getType() {
            return CITEM_OBJECT.getType();
        }

        public int getJdbcType() {
            return CITEM_OBJECT.getJdbcType();
        }

        public boolean isDelimited() {
            return CITEM_OBJECT.isDelimited();
        }

        public String delimitedName() {
            return CITEM_OBJECT.delimitedName();
        }

        public String delimitedAliasName() {
            return CITEM_OBJECT.delimitedAliasName();
        }
    }
}